Repository MapColonies/GpkgMerger, pull requests merged in 2024-01, with the labels that each got.

#132 feat(service): add memory limit to batch size
  MergerService/appsettings.Development.json
  MergerService/appsettings.json
  MergerService/src/run.cs
  helm/templates/deployment.yaml
  helm/values.yaml
Labels: enhancement

#131 refactor: remove dependency for TileFormatter and determine tile form…
  MergerLogic/Batching/Tile.cs
  MergerLogic/Clients/FileClient.cs
  MergerLogic/Clients/GpkgClient.cs
  MergerLogic/Clients/HttpSourceClient.cs
  MergerLogic/Clients/S3Client.cs
  MergerLogic/DataTypes/Fs.cs
  MergerLogic/Extensions/ServiceCollectionExtensions.cs
  MergerLogic/ImageProcessing/IImageFormatter.cs
  MergerLogic/ImageProcessing/ImageFormatter.cs
  MergerLogic/ImageProcessing/TileMerger.cs
  MergerLogic/Utils/DataUtils.cs
  MergerLogic/Utils/IPathUtils.cs
  MergerLogic/Utils/PathUtils.cs
  MergerLogic/Utils/UtilsFactory.cs
  MergerLogicUnitTests/Batching/TileTest.cs
  MergerLogicUnitTests/Clients/FileClientTest.cs
  MergerLogicUnitTests/DataTypes/FSTest.cs
  MergerLogicUnitTests/DataTypes/GpkgTest.cs
  MergerLogicUnitTests/DataTypes/S3Test.cs
  MergerLogicUnitTests/DataTypes/TMSTest.cs
  MergerLogicUnitTests/DataTypes/WMTSTest.cs
  MergerLogicUnitTests/DataTypes/XYZTest.cs
  MergerLogicUnitTests/Utils/GeoUtilsTest.cs
  MergerLogicUnitTests/Utils/GpkgUtilsTest.cs
  MergerLogicUnitTests/Utils/HttpSourceUtilsTest.cs
  MergerLogicUnitTests/Utils/OneXOneConvertorTest.cs
  MergerLogicUnitTests/Utils/PathUtilsTest.cs
  MergerLogicUnitTests/Utils/S3UtilsTest.cs
Labels: Refactor

#133 refactor: change service run structure and add test coverage
  GpkgMerger.sln
  MergerLogic/DataTypes/Coord.cs
  MergerLogic/ImageProcessing/ImageFormatter.cs
  MergerLogic/ImageProcessing/TileMerger.cs
  MergerLogic/ImageProcessing/TileScaler.cs
  MergerLogic/Utils/ImageUtils.cs
  MergerLogicUnitTests/ImageProcessing/ImageFormatterTest.cs
  MergerLogicUnitTests/ImageProcessing/TestImages/1.png
  MergerLogicUnitTests/ImageProcessing/TestImages/1_upscaled_16_17.png
  MergerLogicUnitTests/ImageProcessing/TestImages/2.png
  MergerLogicUnitTests/ImageProcessing/TestImages/2_1_merged.png
  MergerLogicUnitTests/ImageProcessing/TestImages/3.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/3_1_merged.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/3_1_merged_upscaled_14_15.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/3_1_merged_upscaled_5_15.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/3_4_merged.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/3_upscaled_9_10.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/4.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/4_upscaled_3_13.jpeg
  MergerLogicUnitTests/ImageProcessing/TestImages/5.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_24bit.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_24bit_upscaled_16_18.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_32bit.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_64bit.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_8bit.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_8bit_upscaled_16_18.png
  MergerLogicUnitTests/ImageProcessing/TestImages/5_upscaled_16_18.png
  MergerLogicUnitTests/ImageProcessing/TestImages/empty_tile.png
  MergerLogicUnitTests/ImageProcessing/TestImages/invalid_image
  MergerLogicUnitTests/ImageProcessing/TileMergerTest.cs
  MergerLogicUnitTests/ImageProcessing/TileScalerTest.cs
  MergerLogicUnitTests/Utils/ImageUtilsTest.cs
  MergerLogicUnitTests/Utils/TestData/full_transparent.png
  MergerLogicUnitTests/Utils/TestData/no_transparency.jpeg
  MergerLogicUnitTests/Utils/TestData/no_transparency.png
  MergerLogicUnitTests/Utils/TestData/partial_transparent.png
  MergerService/Program.cs
  MergerService/Runners/IMainRunner.cs
  MergerService/Runners/ITaskExecutor.cs
  MergerService/Runners/ITaskRunner.cs
  MergerService/Runners/MainRunner.cs
  MergerService/Runners/TaskExecutor.cs
  MergerService/Runners/TaskRunner.cs
  MergerService/Utils/JobUtils.cs
  MergerService/Utils/TaskUtils.cs
  MergerService/src/IRun.cs
  MergerServiceUnitTests/MergerServiceUnitTests.csproj
  MergerServiceUnitTests/Runners/TaskExecutorTest.cs
  MergerServiceUnitTests/Runners/TaskRunnerTest.cs
  MergerServiceUnitTests/Runners/TestData/tile.jpeg
  MergerServiceUnitTests/Utils/JobUtilsTest.cs
  MergerServiceUnitTests/Utils/TaskUtilsTest.cs
Labels: Feature Testing

#134 fix(merger-cli): docker image builds without runtime
  .dockerignore
  MergerCli/Dockerfile
Labels: bug

#136 refactor: change source building location
  MergerLogic/Monitoring/Metrics/IMetricsProvider.cs
  MergerLogic/Monitoring/Metrics/MetricsProvider.cs
  MergerService/Runners/TaskExecutor.cs
Labels: Refactor
